name: Compare functions
on: push
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }} # true
          CONTAINS_ARR_FUNC: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
          STARTS_WITH_FUNC: ${{ startsWith('Hello', 'He') }} # true
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }} # true
